name: lector_qr
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_barcode_scanner: ^2.0.0
  path_provider: ^2.1.3
  sqflite: ^2.3.2
  url_launcher: ^6.2.4
  google_maps_flutter: ^2.5.2
  webview_flutter: ^4.5.0
  upgrader: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
